"""The shape of the code itself: how big its functions are, what it repeats,
what it generates, what it declares as a type, and what it says is on its way
out.
"""

import ast
import os
import re

from ..walk import _cached, _lines_matching, _slurp


def data_flow(ctx) -> dict:
    """Which handler touches which table, by co-occurrence in a file."""
    _read = ctx.read
    code_files = ctx.code_files
    data_flow = {}
    for rel in code_files:
        body = _read(rel)
        if not body:
            continue
        eps = re.findall(r"[\"\'`](/[\w/{}.:-]{2,60})[\"\'`]", body)[:20]
        tbls = re.findall(r"\b(?:FROM|INTO|UPDATE|JOIN)\s+([a-z_][\w.]{2,40})", body, re.I)[:20]
        if eps and tbls:
            data_flow[rel] = {"paths": sorted(set(eps))[:8], "tables": sorted(set(tbls))[:8]}
    data_flow = dict(list(data_flow.items())[:25])
    return {"data_flow": data_flow}


def deprecations(ctx) -> dict:
    """Deprecations and API versions the code announces."""
    _read = ctx.read
    code_files = ctx.code_files
    deprecations = {}
    api_versions = set()
    for rel in code_files:
        body = _read(rel)
        if not body:
            continue
        dep = _lines_matching(body, ('@deprecated', 'deprecated', 'deprecationwarning'), 4)
        if dep:
            deprecations[rel] = [d.strip()[:120] for d in dep]
        api_versions.update(re.findall(r"/(v\d+(?:\.\d+)?)/", body)[:10])
    deprecations = dict(list(deprecations.items())[:20])
    return {"api_versions": api_versions, "deprecations": deprecations}


def generated(ctx) -> dict:
    """Generated code, and what it was generated from: editing the artefact is
    a mistake the map can prevent."""
    code_files = ctx.code_files
    repo = ctx.repo
    generated = {}
    for rel in code_files:
        body = _slurp(os.path.join(repo, rel), 4000)
        m3 = re.search(r"(?:Code generated by|@generated|AUTO-?GENERATED|DO NOT EDIT)"
                       r"[^\n]{0,90}", body, re.I)
        if m3:
            generated[rel] = m3.group(0).strip()[:110]
    generated = dict(list(generated.items())[:40])
    return {"generated": generated}


def types_declared(ctx) -> dict:
    """The type surface: interfaces, protocols, enums and dataclasses."""
    code_files = ctx.code_files
    repo = ctx.repo
    types_declared: dict[str, list] = {}
    for rel in code_files:
        body = _slurp(os.path.join(repo, rel))
        if not body:
            continue
        names = re.findall(r"export\s+(?:type|interface|enum)\s+(\w+)", body)
        names += re.findall(r"class\s+(\w+)\s*\((?:\w*Protocol|\w*Enum|BaseModel)\)", body)
        names += re.findall(r"@dataclass[\s\S]{0,40}?class\s+(\w+)", body)
        names += re.findall(r"^type\s+(\w+)\s+(?:struct|interface)", body, re.M)
        if names:
            types_declared[rel] = sorted(set(names))[:20]
    types_declared = dict(sorted(types_declared.items(), key=lambda kv: -len(kv[1]))[:40])
    return {"types_declared": types_declared}


def license_headers(ctx) -> dict:
    """License headers, where files carry them."""
    code_files = ctx.code_files
    repo = ctx.repo
    license_headers: dict[str, int] = {}
    for rel in code_files[:4000]:
        head = _slurp(os.path.join(repo, rel), 600)
        m5 = re.search(r"(?:SPDX-License-Identifier:\s*([\w.+-]+)"
                       r"|Licensed under the ([\w ]{3,40}) License"
                       r"|Copyright \(c\) [\d-]+ ([\w .,-]{3,40}))", head)
        if m5:
            key = next(x for x in m5.groups() if x).strip()
            license_headers[key] = license_headers.get(key, 0) + 1
    license_headers = dict(sorted(license_headers.items(), key=lambda kv: -kv[1])[:10])
    return {"license_headers": license_headers}


def complexity(ctx) -> dict:
    """Size and shape of functions: where the complexity actually sits."""
    code_files = ctx.code_files
    repo = ctx.repo
    complexity = []
    for rel in code_files:
        if not rel.endswith(".py"):
            continue
        full = os.path.join(repo, rel)

        def _complexity_of(full=full, rel=rel):
            try:
                tree = ast.parse(_slurp(full))
            except (SyntaxError, ValueError):
                return []
            found = []
            for node in ast.walk(tree):
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                branches = sum(isinstance(x, (ast.If, ast.For, ast.While, ast.Try,
                                              ast.BoolOp, ast.ExceptHandler))
                               for x in ast.walk(node))
                length = (getattr(node, "end_lineno", node.lineno) or node.lineno) - node.lineno
                if branches >= 8 or length >= 80:
                    found.append(f"{os.path.basename(rel)}:{node.name} "
                                 f"({length} lines, {branches} branches)")
            return found

        complexity += _cached(full, "complexity", _complexity_of)
    complexity = sorted(complexity, key=lambda x: -int(re.search(r"\((\d+) lines", x).group(1)))[:25]
    return {"complexity": complexity}


def clones(ctx) -> dict:
    """Blocks of code that appear more than once, by their shape."""
    code_files = ctx.code_files
    repo = ctx.repo
    clones: dict[str, list] = {}
    seen_blocks: dict[str, list] = {}
    for rel in code_files:
        if not rel.endswith((".py", ".ts", ".js", ".go", ".java")):
            continue
        lines_ = [l.strip() for l in _slurp(os.path.join(repo, rel)).splitlines()
                  if l.strip() and not l.strip().startswith(("#", "//", "*"))]
        for i in range(0, max(0, len(lines_) - 8), 4):
            block = "\n".join(lines_[i:i + 8])
            if len(block) < 120:
                continue
            key = str(hash(block))
            seen_blocks.setdefault(key, []).append(f"{rel}:{i}")
    for key, places in seen_blocks.items():
        if len(places) > 1:
            clones[places[0]] = places[1:6]
    clones = dict(list(clones.items())[:20])
    return {"clones": clones}
